// app/layout.js
import { Playfair_Display } from "next/font/google";
import "./globals.css";
import Header from "./components/Header";
import Example from "./components/Header";
import Footer from "./components/Footer";
import Head from "next/head";
// import CursorEffect from "./components/CursorEffect";

const playfairDisplay = Playfair_Display({
  variable: "--font-playfair-display",
  subsets: ["latin"],
  weight: ["400", "500", "700"], // Specify the font weights you need
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <Head>
        {/* Include Razorpay Checkout Script */}
        <script src="https://checkout.razorpay.com/v1/checkout.js"></script>
      </Head>
      <body className={`${playfairDisplay.variable} antialiased`}>
        {/* Header component */}
        {/* <CursorEffect/> */}
        
        <Example/>
        {children}
        {/* Footer component */}
        <Footer />
      </body>
    </html>
  );
}
